# Generated by Django 3.1.7 on 2022-12-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='nameZone',
            field=models.ForeignKey(blank=True, db_column='nameZone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.zone'),
        ),
    ]
