# Generated by Django 3.1.7 on 2022-12-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20221211_1025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailinvoice',
            unique_together={('invoiceno', 'stockcode')},
        ),
    ]
