# Generated by Django 3.1.7 on 2022-12-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20221211_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailinvoice',
            old_name='detailInvoice_id',
            new_name='detailinvoice_id',
        ),
    ]
