# Generated by Django 3.1.7 on 2022-12-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20221212_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransfert',
            name='invoicedate',
            field=models.DateField(max_length=25),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoicedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
